Allow reformatting an entire SmalltalkWorkspace if nothing is selected
dolphinsmalltalk/Dolphin pull request #1041
Opened 2020-10-09 18:17 UTC by daniels220

2020-10-09 19:09 UTC, blairmcg requested changes

2020-10-12 16:28 UTC, daniels220 commented on Core/Object Arts/Dolphin/IDE/Base/SmalltalkWorkspace.cls
> +	self hasSelection ifFalse: [self view selectAll].
Eh, it's easy enough, and since I'm fixing the package/categories anyway...

2020-10-15 10:29 UTC, blairmcg commented
@daniels220, inserting a `self view moveToEndOfDocument` as the last statement of the false branch of the final if-statement will fix the test, and then this can be merged. Although only ScintillaView implements the `moveToEndOfDocument` message, it's fine to assume that the view of a workspace will always be a ScintillaView as it can no longer be anything else really.

2020-10-15 10:35 UTC, blairmcg commented
@daniels220, I'll merge this, and then fix the pre-existing test that is failing, since it is just assuming the old rounding behaviour, rather than the new truncating behaviour.

2020-11-03 18:22 UTC, daniels220 commented
Sorry, lost track of this. Added the `moveToEndOfDocument` as you suggested.

2020-11-03 19:16 UTC, merged