Small changes in many files
dolphinsmalltalk/Dolphin pull request #1147
Opened 2021-08-03 00:20 UTC by brickviking

Includes three sets of patches, including removing redundant "the", and a comment I need clarification on what it was meant to include but left out.

Again, an eye over these to see if I missed anything obvious. Thanks for the work you're doing, Blair.

2021-08-03 19:21 UTC, blairmcg requested changes

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Prompters/UI.IntegerPrompter.cls
> +	"Creates an instance of the receiver on aValueModel with an aStringPrompt.
Creates an instance of the receiver on aValueModel and aStringPrompt.

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Text/OS.CHARFORMAT2W.cls
> +	"Private - OR in to contents mask field the bit flags represented by anInteger.
to _the_ contents mask

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Text/OS.CHARFORMAT2W.cls
> +	a Fraction if the, for example, the size is 10.5 points)."
Extraneous the after "a Fraction if"

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Text/OS.PARAFORMAT.cls
> +	"Private - OR in to receiver's mask field the bit flags represented by anInteger.
OR in to _the_ receiver's

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Text/UI.MultilineTextEdit.cls
> +	"Delete the line on which the caret is located into the cut buffer, including the line delimiter (i.e. subsequent lines shift
I think I would say "to the clipboard"

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Text/UI.RichTextEdit.cls
> +	current selection (or from the insertion point if no selection.)"
no selection).

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Text/UI.TextEdit.cls
> +	which Windows does not support directly as an Edit control style."
"functionality, which"
(or without the comma, "functionality that", as you prefer)

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/Tree/UI.TreePresenter.cls
> +TreePresenter conforms to <selectableItems> to provide methods for accessing the current selection. In addition, the <treePresenter> protocol allows the tree presentation to be modified using the #ex
I think the original text is more correct if "navigating" is replaced with "navigated"

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Views/Scintilla/UI.Scintilla.ScintillaView.cls
> +	"Scintilla zooms in and out by points, and is the points delta that is reported by SCI_GETZOOM, which is not easy to understand from a user perspective. The actual the zoom factor is relative to the
and _it_ is the points

2021-08-03 19:21 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Views/Scintilla/UI.Scintilla.ScintillaView.cls
> +	"Scintilla zooms in and out by points, and is the points delta that is reported by SCI_GETZOOM, which is not easy to understand from a user perspective. The actual the zoom factor is relative to the
"The actual ~~the~~ zoom factor"

2021-08-03 19:21 UTC, blairmcg commented on Core/Contributions/Camp Smalltalk/ANSI/Tests/AnsiDB.st
> +It is possible that the time specified does not exist in the local time specified by the implementation. If there is a time change such that the local time is set forward and the time specified is in
In some cases 'the the' is not a doubling up, but rather a mistyping of 'then the'. That is the case here. It either needs the 'then', or a comma before 'the'. I'm not sure why this paragraph is repeated so much, but disregarding that the same would apply to the duplicates too.

2021-08-03 22:56 UTC, brickviking commented on Core/Object Arts/Dolphin/MVP/Base/Graphics.Icon.cls
> +	NtDll isWine ifTrue: [^self null].
Ah, sorry. That one is an attempt to fix the black squares I was getting once you had upscaled Blank.ico to fix issue #1097. Windows seems to downscale the image fine, but for some reason I don't think wine knows quite what to do. I know you don't want to litter the image with a whole lot of useless platform-specific fixes but I was getting the same black squares that #1097 had, though for a different reason. Do you have a better suggestion that would remove the black squares?

My bug report is linked [here in my issue 23](https://github.com/brickviking/Dolphin/issues/23) to keep it out of the flow of general Dolphin bugfixing.

2021-08-03 23:26 UTC, brickviking commented on Core/Object Arts/Dolphin/MVP/Presenters/ListTree/UI.ListTreeView.cls
> +The multi-select version, MultipleSelectionListTreeView, can be used with ListPresenters (e.g. ListPresenter.Multi-select ListTree view) and with ProperTreeViewPresenter.
Down a bit later in the comment (around line 71 before removals), there's mention made of multiple selections in a ListTreeView. Does the primary ListTreeView control support multiple selections as well as single selections?

2021-08-03 23:27 UTC, brickviking commented on Core/Object Arts/Dolphin/MVP/Presenters/ListTree/UI.ListTreeView.cls
> +The big gains over a TreeView is that a ListTreeView supports additional ListViewColumns and that MultipleSelectionListTreeView supports multiple selection (duh).  As far as I know things like per-co
Right. Do I leave in the phrase "As far as I know things like ..."?

2021-08-03 23:54 UTC, brickviking commented on Core/Object Arts/Dolphin/MVP/Presenters/ListTree/UI.ListTreeView.cls
> +	"answer an OrderedCollection of all the items that are currently hidden-expanded; those
Perhaps we could use the following:
```
answer an OrderedCollection of all the items that are currently hidden-expanded. These are 
the ones we will automatically expand as soon as they are visible, ...
```

2021-08-04 01:17 UTC, brickviking commented on Core/Contributions/IDB/ChunkBrowser.cls
> +    	ifFalse: [a identity2 <= b identity2]]' 34 1 138 ##(Smalltalk.PoolDictionary) 992 8 #[252 2 0 1 1 31 0 17 18 230 33 230 32 228 32 158 228 33 158 132 221 8 228 32 159 228 33 159 130 106 228 32 15
Yup, fair call. I've undone those changes. Are those numbers mainly raw Smalltalk commands to be interpreted that I see in the method body?

2021-08-04 01:22 UTC, brickviking commented on Core/Object Arts/Dolphin/MVP/Views/Scintilla/UI.Scintilla.ScintillaView.cls
> +	"Scintilla zooms in and out by points, and is the points delta that is reported by SCI_GETZOOM, which is not easy to understand from a user perspective. The actual the zoom factor is relative to the
Also, how about this?

```
"Scintilla zooms in and out by points, and reports the points delta with SCI_GETZOOM, which is not easy to understand from a user perspective.
```

2021-08-04 17:03 UTC, blairmcg commented
> One other thing, I've found in the defaultResourceLibrary at Core/Object Arts/Dolphin/Base/Core.SessionManager.cls:247
> ...
> Should the withAliases: have 'dolphindr8' added to that list, or does Dolphin already know about that file?

I forgot to answer that. 

No, the list of aliases is things that should map to the lastest resource library if requested instead of it. If you look at `defaultResLibPath` you will see that it returns `DolphinDR8`.

2021-08-04 17:08 UTC, blairmcg commented on Core/Contributions/IDB/ChunkBrowser.cls
> +    	ifFalse: [a identity2 <= b identity2]]' 34 1 138 ##(Smalltalk.PoolDictionary) 992 8 #[252 2 0 1 1 31 0 17 18 230 33 230 32 228 32 158 228 33 158 132 221 8 228 32 159 228 33 159 130 106 228 32 15
They are a representation of serialized objects using only literal values (strings, symbols, ints, booleans, nil, byte arrays, arrays of other literals, and so on). Not so much commands, as data.

2021-08-04 17:11 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Base/Graphics.Icon.cls
> +	NtDll isWine ifTrue: [^self null].
We should deal with that separately. You are right that I don't want to have any of these `isWine` conditions. In most cases it should be possible to work around in another way, although equally I don't want lowest common denominator solutions either as that would be outside the philosophy of what Dolphin was originally intended to be (i.e. a native Windows Smalltalk).

2021-08-04 17:12 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/ListTree/UI.ListTreeView.cls
> +The big gains over a TreeView is that a ListTreeView supports additional ListViewColumns and that MultipleSelectionListTreeView supports multiple selection (duh).  As far as I know things like per-co
Yes. This code and the comments were originally written by Chris Uppal. I don't think we should change his comments unless they are inaccurate.

2021-08-04 17:13 UTC, blairmcg commented on Core/Object Arts/Dolphin/MVP/Presenters/ListTree/UI.ListTreeView.cls
> +	"answer an OrderedCollection of all the items that are currently hidden-expanded; those
Again, I don't feel it is appropriate to change the writing style in contributions. It forms part of the contribution.

2021-08-04 21:45 UTC, brickviking commented on Core/Object Arts/Dolphin/MVP/Base/Graphics.Icon.cls
> +	NtDll isWine ifTrue: [^self null].
Okay, I'll drop it out of the PR. But man those black squares look ugly. :)
Makes me wonder what stuff Jgfoster did to get his image to work, it appears to be a 99.5% vanilla Dolphin.

2021-08-05 07:53 UTC, merged